### PR TITLE
Fix for "Invalid scheme format"

### PR DESCRIPTION
**Pull request by dwbutler**
Fixes https://github.com/bblimke/webmock/issues/489. See https://github.com/sporkmonger/addressable/issues/208

### CODE REVIEW

**Comment by bblimke** [comment]
Thanks.

Most likely the result of heuristic parse will be the same for all variations of the url string, therefore multiple checks might be redundant. I need to think about it.
On the other side I'm not sure if precision won't be lost when converting the string to the url created with heuristic_parse. 
All specs pass, but I need to make sure that none are missing.

**Comment by skunkworker** [comment]
:+1:  on the patch, it fixed the issues I was having with an addressable template and webmock.

**Comment by tmertens** [comment]
@bblimke any update on this?

**Comment by oliakremmyda** [comment]
The following specs are failing:
```
rspec ./spec/unit/request_pattern_spec.rb:114 # WebMock::RequestPattern when matching should match if uri Addressable::Template pattern matches unescaped form of request uri
rspec ./spec/unit/request_pattern_spec.rb:119 # WebMock::RequestPattern when matching should match if uri Addressable::Template pattern matches request uri
rspec ./spec/unit/request_pattern_spec.rb:161 # WebMock::RequestPattern when matching when parameters are escaped should match if uri Addressable::Template pattern matches uri without parameter value and request has escaped parameters
rspec ./spec/unit/request_pattern_spec.rb:166 # WebMock::RequestPattern when matching when parameters are escaped should match if uri Addressable::Template pattern matches uri without parameter value and request has unescaped parameters
rspec ./spec/unit/request_pattern_spec.rb:171 # WebMock::RequestPattern when matching when parameters are escaped should match if uri Addressable::Template pattern matches uri with unescaped parameter value and request has unescaped parameters
rspec ./spec/unit/request_pattern_spec.rb:176 # WebMock::RequestPattern when matching when parameters are escaped should match if uri Addressable::Template pattern matches uri with escaped parameter value and request has escaped parameters
rspec ./spec/unit/request_pattern_spec.rb:222 # WebMock::RequestPattern when matching when matching requests on query params when uri is described as Addressable::Template should raise error if query params are specified
rspec ./spec/unit/request_pattern_spec.rb:232 # WebMock::RequestPattern when matching when matching requests on query params when uri is described as Addressable::Template should match when query params are declared as HashIncluding matcher matching params
rspec ./spec/unit/request_pattern_spec.rb:244 # WebMock::RequestPattern when matching when matching requests on query params when uri is described as Addressable::Template should match when query params are declared as RSpec HashIncluding matcher matching params
```

**Pull request closed without merging**
