### PR TITLE
Fix: Suggested stub body to_return should be valid JSON when request header contains 'Accept'=>'application/json'. It now suggests a return body with '{}'.

### PR DESCRIPTION
**Pull request by redbar0n**

### CODE REVIEW

**Comment by redbar0n** [comment]
RE: https://github.com/bblimke/webmock/issues/688

**Comment by redbar0n** [comment]
All tests ran green locally. Not sure why the Travis CI build failed.

› bundle exec rake test
Loaded suite /Users/Magne/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/rake_test_loader
Started
............

Finished in 0.030351 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
12 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
395.37 tests/s, 461.27 assertions/s

**Comment by bblimke** [comment]
@redbar0n `bundle exec rake`

`rake test` only runs test unit tests.

**Comment by redbar0n** [comment]
Ok. Anything I need to do?

**Comment by bblimke** [comment]
@redbar0n the code is broken as tests show, so it needs to be fixed before merging :)

Then I'd fix the duplication I mentioned it the comment, unless you have a different opinion?

**Comment by redbar0n** [comment]
Ok. I'm not sure how to fix Travis CI test failures. 

Duplication? I can't find the comment you're referring to.

**Comment by bblimke** [comment]
https://github.com/bblimke/webmock/pull/691#discussion_r105141327

**Comment by redbar0n** [comment]
Done. :)

**Comment by bblimke** [comment]
@redbar0n sorry, perhaps I wasn't clear.

When I asked 'is the first & necessary?', I referred to semantics not to the syntax.
Why do you need to check if `request_pattern` is present?

I don't think you have addressed my comment regarding duplication yet :)

**Comment by redbar0n** [comment]
I see. I don't know if request_pattern can ever be nil, so I just check just in case. But if it cannot then that check can just be removed.

Was you comment regarding duplication the #691 (comment) link you gave? I can't access it for some reason. It just takes me to this same page.

**Comment by bblimke** [comment]
You have to click on `Show outdated` to see the comment.

If there was a need for request_pattern checking then specs would fail if it was missing.

**Comment by redbar0n** [comment]
Where do I find `Show outdated` on github? I can't see it anywhere on this page.

**Comment by oliakremmyda** [comment]
Since the tests are passing now can we merge this PR?

**Comment by oliakremmyda** [comment]
Also, I think it would be a good idea to squash all these commits into a single one :)

**Comment by bblimke** [comment]
@oliakremmyda we can, indeed 👍 thanks for reminding about this. feel free to merge it.

**Pull request merged**
