### PR TITLE
Add hash excluding matcher to query option

### PR DESCRIPTION
**Pull request by Warrior109**

### CODE REVIEW

**Comment by bblimke** [comment]
@Warrior109 thank you.

I believe that the actual `hash_excluding` method implementation is missing.

There are also specs missing that would verify that `hash_excluding` behaviour,
which would show that it's missing.

It's also worth updating the README

**Comment by Warrior109** [comment]
I added hash_excluding_matcher_spec.rb with test hash excluding matcher. And i updated a Readme.md.

**Comment by bblimke** [comment]
@Warrior109 you have added matcher and the spec for the matcher but you have not integrated hash_including into the webmock api and not tested it (in specs or tests)
Please see where hash_including is referenced in webmock https://github.com/bblimke/webmock/search?utf8=%E2%9C%93&q=hash_including&type=

**Comment by Warrior109** [comment]
What about this version? All it`s ok? Or, maybe, i must do something again?

**Comment by bblimke** [comment]
Almost there :)

One example in each of these 3 specs.

`test/shared_test.rb`
`spec/acceptance/shared/stubbing_requests.rb`
`spec/acceptance/shared/request_expectations.rb`

Looking at api_spec.rb examples I suggest using a hash that contains some some values and doesn't contain other values, and asserting a match instead of just copy and paste and changing `to` to `not_to`

**Comment by Warrior109** [comment]
What about this version?)

**Comment by bblimke** [comment]
Looking good now 👍

**Comment by Warrior109** [comment]
Thanks a lot.)

**Comment by bblimke** [comment]
Released as version 3.1.0. I'm sorry for the delay releasing it.

**Pull request merged**
