### PR TITLE
Make the Typhoeus adapter also read the Authorization header for user info

### PR DESCRIPTION
**Pull request by knu**
When using Typhoeus via Faraday, the :userpwd option is never used because Faraday is a backend independent framework in which Faraday::Request::BasicAuthentication handles basic authentication simply by setting the Authorization header without bothering with any backend specific option.

### CODE REVIEW

**Comment by bblimke** [comment]
@knu thanks for the pull request.

The code requires refactoring (extracting to methods) before it could be merged and some test to verify that behaviour.

I'm concerned about removing the authorization header. In case the request stub expected the header to be present. Any thoughts?

**Comment by knu** [comment]
Hi, thanks for taking a look.

Yes, this is just a bug report with a minimal patch and really needs some test.

As for the header removal, other adapters are doing this so I just followed that:
- https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/net_http.rb#L290
- https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/httpclient_adapter.rb#L211

The original problem is here, that you have to change how to mock a request with basic auth dependent on the backend library:
https://github.com/cantino/huginn/pull/1340/files#diff-502af1f8d307aaf7af861f16d2688b86R1040

**Comment by knu** [comment]
Perhaps the Authorization header should not be removed in all adapters in the first place because it makes it impossible to mock a request specifying the Authorization header.

**Comment by bblimke** [comment]
@knu yes, and that's the change in WebMock 2.0. https://github.com/bblimke/webmock/blob/2.0/CHANGELOG.md 
it's currently released as 2.0.0.beta1

**Comment by knu** [comment]
Cool!  I'd really appreciate your decision to make the change taking advantage of the timing of starting off a new major version series.  Thank you!

**Pull request closed without merging**
