### PR TITLE
Fixed HTTP gems mock

### PR DESCRIPTION
**Pull request by zanker**
With http 0.8.0.pre the format changed slightly, this makes it work with both pre-0.8 and post.

cc @ixti @tarcieri

### CODE REVIEW

**Comment by tarcieri** [comment]
I'd suggest renaming `http_gem` -> `http_rb`

**Comment by zanker** [comment]
Done

**Comment by ixti** [comment]
@zanker would be awesome if you will merge this one as well:
https://github.com/bblimke/webmock/pull/397

**Comment by zanker** [comment]
What needs to be done for #397, or you just mean pull that into this?

**Comment by ixti** [comment]
@zanker yeah, just merge it in. It "normalizes" `HTTP::Response::Status` :D

**Comment by zanker** [comment]
@ixti sure, done

**Comment by ixti** [comment]
@zanker Thanks!
@bblimke It can be merged. Failed specs are not related to this PR (except probably for ruby 1.8.7, which we do not support in http.rb since 0.7.x)

**Comment by bblimke** [comment]
@ixti it seems the failed specs are related to this PR.

I'm getting this error in most examples.

````
       uninitialized constant WebMock::HttpLibAdapters::HttpGemAdapter
     # ./spec/../lib/webmock/http_lib_adapters/http_rb/client.rb:11:in `webmock_enabled?'
````

Master is now green.

**Comment by ixti** [comment]
@bblimke Sorry I missed that. Will provide a fixed version in a sec.

**Pull request closed without merging**
