### PR TITLE
#915 - Prevent overwriting teardown

### PR DESCRIPTION
**Pull request by jessebs**

### CODE REVIEW

**Comment by bblimke** [comment]
Hi @jessebs 

Could you please explain how that works?

**Comment by jessebs** [comment]
Sure.  Take a look at https://test-unit.github.io/test-unit/en/Test/Unit/TestCase.html#teardown-instance_method

Based on that, there are several options for implementing a teardown.  Implementing this way means that a subclass overwriting the teardown won't overwrite the webmock teardown functionality.

I believe that users should be able to overwrite the teardown_with_webmock method to alter that behavior should they really desire it.

**Comment by bblimke** [comment]
Oh wow. Now I'm curious how that works. I mean, how is that `teardown` invocation before method definition implemented internally in test::unit

**Comment by jessebs** [comment]
I just confirmed that overwriting the teardown_with_webmock method in the test class will replace the behavior.

**Comment by jessebs** [comment]
I haven't dug into test::unit to see how it's implemented, but it was definitely a surprise when I found that.

**Comment by jessebs** [comment]
`teardown` is a class method that accepts method names and blocks.  Nothing really fancy but it's a pretty neat way of doing things

**Comment by bblimke** [comment]
@jessebs but there are neither args nor block passed to the `teardown` method in your implementations.
The `teardown_with_webmock` method is declared in the next line, therefore how is it associated with the `teardown` invocation in the previous line?

**Comment by jessebs** [comment]
```
def my_method(*method_names, &callback)
  p method_names
  p callback
end

my_method def example
end
```

**Comment by jessebs** [comment]
Good point.  If it was on the same line that would make sense, but it's not.

Take a look at fixture.rb in the test unit codebase.  I think that holds the answer, but I'm not really able to give it my full attention right now.

**Comment by jessebs** [comment]
Any idea why travis hasn't started building?

**Comment by bblimke** [comment]
Screenshot 2020-11-06 at 18 49 23

**Comment by jessebs** [comment]
@bblimke Travis still appears to be sitting on the build.  Any thoughts?  The PR is no longer a draft

**Comment by bblimke** [comment]
It's released as version 3.9.5. Thank you @jessebs

**Comment by jessebs** [comment]
Thanks for the quick merge!

**Pull request merged**
