### PR TITLE
Add Ruby 2.4.0 compatibility to 1.x

### PR DESCRIPTION
**Pull request by matthewrudy**
Cherry pick the "Support Ruby 2.4' commit into the 1.x branch

### CODE REVIEW

**Comment by bblimke** [comment]
@matthewrudy sorry but 1.x is compatible with ruby 1.9 and this change is incompatible with ruby 1.9

**Comment by matthewrudy** [comment]
@bblimke true.
Wasn't thinking about.

Let's just close this.

thanks.

**Comment by bblimke** [comment]
@matthewrudy why would you like to use ruby 2.4 with webmock 1.x? Why not move to webmock 2.x?

**Comment by matthewrudy** [comment]
@bblimke because for some reason 2.x totally breaks for me
And I can't work it out.

Something to do with vcr and webmock's interaction.

I should have another go, shouldn't I.

**Comment by bblimke** [comment]
You might need to convert your vcr cassettes. Please see https://github.com/vcr/vcr/issues/570

**Comment by matthewrudy** [comment]
@bblimke wow,
that was it.

spent ages thinking it was because of our custom vcr matcher,
but it was just the vcr cassette.

ran this script!
https://gist.github.com/glaszig/9170b1cf2186674faeead74a68606c5d

thanks for your help!!!

**Pull request closed without merging**
