### PR TITLE
Add a hint to the error message raised when `with` method is called w…

### PR DESCRIPTION
**Pull request by asok**
…ithout block

Related to #174

### CODE REVIEW

**Comment by asok** [comment]
WDYT?

**Comment by bblimke** [comment]
@asok thanks! That's a good idea. It happened to me so many times, not necessarily with WebMock.

**Comment by tijmenb** [comment]
@asok I just got this excellent error message, and came here to thank you! Very helpful. 💯

**Comment by asok** [comment]
So nice to get a simple, direct thank you :)

**Pull request merged**
