### PR TITLE
* Fix Travis build for Ruby 1.8.7

### PR DESCRIPTION
**Pull request by PikachuEXE**
For #570

### CODE REVIEW

**Comment by davidbegin** [comment]
:+1: awesome. Thanks for opening this. It looks good to me.

So If this looks good to @bblimke and @matthewrudy I'll update the changelog. And we can get this released finally!

**Comment by bblimke** [comment]
looks awesome! :)

**Comment by davidbegin** [comment]
Great, so I will Runtime error and Changelog, and get a release out today!

**Comment by davidbegin** [comment]
got distracted yesterday. So I am working on the release now.

**Pull request merged**
