### PR TITLE
Add suport to match body on PATCH for Curb

### PR DESCRIPTION
**Pull request by lucasgomide**

### CODE REVIEW

**Comment by lucasgomide** [comment]
The build broke, look at #637

**Comment by bblimke** [comment]
This should be compatible with taf2/master branch.

Since it's not released yet and it's possible it's going to be changed again,
I'm thinking about reverting support for Curb.patch completely,
and just keep it on branch (or onpull request), until Curb with patch support
is officially released.

**Comment by lucasgomide** [comment]
I'm not understand when you say: `until Curb with patch support is officially released.`. 
Because it's possible make request using PATCH on Curb.

I'll remake this to be compatible with taf2/master branch. But before need revert #625 

What do you think ?

**Comment by bblimke** [comment]
I thought it's only possible to do patch requests with Curb from master.

If specs are going to pass against latest Curb 9.3, then it's fine.

I'd like to avoid having dependencies on development versions from github,
since these are likely to change again.

**Comment by lucasgomide** [comment]
Great. You are right !

**Comment by lucasgomide** [comment]
@bblimke i'll close it, because on #639 has the revert necessary to work using the last release of curb

**Pull request closed without merging**
