### PR TITLE
Revert curb patch

### PR DESCRIPTION
**Pull request by lucasgomide**
The feature to turn on debug for curb callbacks was deleted to. It's necessary implement again ):

### CODE REVIEW

**Comment by bblimke** [comment]
The diff is not very clear https://github.com/bblimke/webmock/pull/638/files

**Comment by lucasgomide** [comment]
I don't know why it's happened to be honest. Only deleted the commits with rebase, any suggestion ?

**Comment by bblimke** [comment]
Can you please share, how you have deleted these commits?

**Comment by lucasgomide** [comment]
Sure !

```
git rebase -i 8d82115
````
```
d 20f41cb Add support for PATCH
d 1584414 Uncommented block
d 1f9723b Remove byebug dependency
# d 78ba376a790ce20128cd13b32a15f38be7f6ef1a Trigger
d 983308a Remove not needed line :)
pick 82e3d27 Version 2.1.0
pick 3b62c71 Disabled response decoding in em-http-request specs to make specs more reliable when testing against real requests to third party services.
pick a8e636c Better way to ensure em-http-requests don’t require compressed response by default in specs.
```
```
git reset # Because The previous cherry-pick is now empty, possibly due to conflict resolution.
```
```
git rebase --continue
```

**Comment by bblimke** [comment]
Please correct me if I'm wrong, but is it a good idea to remove the commits from the history?

If anyone has made any changes that depended on the history of commits, or uses WebMock as a gem with commit hash specified, it's going to get very messy.

Why not simple git revert that keeps the whole history?

**Comment by lucasgomide** [comment]
Hm, good..

**Comment by lucasgomide** [comment]
@bblimke can you review please ?

**Comment by bblimke** [comment]
That's better

**Comment by lucasgomide** [comment]
@bblimke sometimes travis break on random ruby versions, do you know what's can be happen ?

**Comment by lucasgomide** [comment]
@bblimke do you have some comment ? Can merge it ?

**Comment by bblimke** [comment]
Looks good :)

**Comment by lucasgomide** [comment]
@bblimke txs

**Pull request merged**
