### PR TITLE
Pretty print failure output

### LINKED ISSUE #713: Better test failure output
Pardon my french, but how is anyone supposed to read this mess?

```
       stub_request(:post, "http://remote.com/api/organizations/link").
         with(body: {"organizations"=>[{"id"=>"200", "product_id"=>"LocalProductId"}, {"id"=>"100", "name"=>"Local org name", "product_id"=>"MyIdentiferHash"}]},
              headers: {'Accept'=>'*/*', 'Authorization'=>'Basic TG9jYWxQcm9kdWN0SWQ6VEVTVF9BUFBfU0VDUkVU', 'Content-Type'=>'application/x-www-form-urlencoded', 'Date'=>'Thu, 10 Aug 2017 16:00:41 GMT', 'User-Agent'=>'Rack::OAuth2 (1.6.2) (2.8.3, ruby 2.2.5 (2016-04-26))'}).
         to_return(status: 200, body: "", headers: {})

       registered request stubs:

       stub_request(:post, "http://initiator.com/api/organizations/link").
         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\",\"name\":\"Remote org name\"}]"})
       stub_request(:post, "http://remote.com/api/organizations/link").
         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\"}]"})
```

I have to copy and paste the error and clean it up so I can even see whats happening.

Just getting rid of the headers / reformatting is a huge help already.

```
       stub_request(:post, "http://remote.com/api/organizations/link").
         with(body: {"organizations"=>[{"id"=>"200", "product_id"=>"LocalProductId"}, {"id"=>"100", "name"=>"Local org name", "product_id"=>"MyIdentiferHash"}]},

       registered request stubs:

         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\",\"name\":\"Remote org name\"}]"})
         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\"}]"})
```

Or formatting it better if you don't want to lose the headers.

```
       stub_request(:post, "http://remote.com/api/organizations/link").
         with(
          body: {
            "organizations"=>[{"id"=>"200", "product_id"=>"LocalProductId"}, {"id"=>"100", "name"=>"Local org name", "product_id"=>"MyIdentiferHash"}
          ]},
          headers: {
            'Accept'=>'*/*',
            'Authorization'=>'Basic TG9jYWxQcm9kdWN0SWQ6VEVTVF9BUFBfU0VDUkVU',
            'Content-Type'=>'application/x-www-form-urlencoded',
            'Date'=>'Thu, 10 Aug 2017 16:00:41 GMT',
            'User-Agent'=>'Rack::OAuth2 (1.6.2) (2.8.3, ruby 2.2.5 (2016-04-26))'
          }).
         to_return(status: 200, body: "", headers: {})

       registered request stubs:

       stub_request(:post, "http://initiator.com/api/organizations/link").
         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\",\"name\":\"Remote org name\"}]"})
       stub_request(:post, "http://remote.com/api/organizations/link").
         with(body: {"organizations"=>"[{\"id\":100,\"product_id\":\"MyIdentiferHash\",\"name\":\"Local org name\"},{\"id\":200,\"product_id\":\"LocalProductId\"}]"})
```

What would be better is if we could get a diff (at least when the requests are close enough) like what RSpec already does. (but I understand there are challenges).

Luckily, most of the test I write don't touch webmock at all so I don't have to deal with this too often.

### PR DESCRIPTION
**Pull request by Olia-Kremmyda**
Fixes #713

### CODE REVIEW

**Comment by bblimke** [comment]
@Olia-Kremmyda Thank you for the pull request.

Am I correct that it does not put the first header in a separate line,
and also doesn't put the curly brackets into separate lines?
In that case, the first header will be misaligned with the rest of the headers.

Why not applying the formatting from this comment?  https://github.com/bblimke/webmock/issues/713#issue-249400184

**Comment by Olia-Kremmyda** [comment]
Hi @bblimke, 

Thank you for your comment and sorry for my late response! 
Are you referring to [this line](https://github.com/Olia-Kremmyda/webmock/blob/c27d7cb296ca24407a4fdc4463a4edbb369e7b10/lib/webmock/stub_request_snippet.rb#L14) as the first header?  

If yes, this is the first log that I guested that I should not change it, please advise me if I should also change this. The output now is something like this:
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST http://www.example.com/ with body 'abcd' with h
eaders {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Length'=>'4', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:

stub_request(:post, "http://www.example.com/").
  with(body: "abcd",
       headers: {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Length'=>'4', 'User-Agent'=>'Ruby'}).
  to_return(status: 200, body: "", headers: {})

registered request stubs:

stub_request(:post, "http://www.example.com/").

  with(body: "abc",
       headers: {'Content-Length'=>'3'})
```

Currently, I have separated only body with header as a first step. I will continue separating the header as well.

**Comment by Olia-Kremmyda** [comment]
Example output:

```
/user/code/webmock/lib/webmock/http_lib_adapters/net_http.rb:114:in `request': Real HTTP connections are disabled. Unregistered request: POST http://www.example.com/ with body '{"organizations"=>[{"id"=>"200", "product_id"=>"LocalProductId"}, {"id"=>"100", "name"=>"Local org name", "product_id"=>"MyIdentiferHash"}]}' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Length'=>'4', 'User-Agent'=>'Ruby'} (WebMock::NetConnectNotAllowedError)

You can stub this request with the following snippet:

stub_request(:post, "http://www.example.com/").
  with(
    body:
	 {"organizations"=>[{"id"=>"200", "product_id"=>"LocalProductId"}, {"id"=>"100", "name"=>"Local org name", "product_id"=>"MyIdentiferHash"}]},
    headers: {
	  'Accept'=>'*/*',
	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
	  'Content-Length'=>'4',
	  'User-Agent'=>'Ruby'
	 }).
  to_return(status: 200, body: "", headers: {})

registered request stubs:

stub_request(:post, "https://www.google.gr/search?q=test").
  with(
    body:
	 "abcdefg",
    headers: {
	  'Content-Length'=>'3'
	 })
stub_request(:post, "http://www.example.com/").
  with(
    body:
	 "abc",
    headers: {
	  'Content-Length'=>'3'
	 })
```

**Comment by bblimke** [comment]
How about the following?

````
stub_request(:post, "http://www.example.com/").
  with(
    body: "abc",
    headers: {
      'Content-Length'=>'3'
    })
````

**Comment by Olia-Kremmyda** [comment]
Sure, I can change this, for the registered request stubs only or for all the cases?

**Comment by bblimke** [comment]
@Olia-Kremmyda I guess it makes sense to change it for everything? What do you think?

**Comment by Olia-Kremmyda** [comment]
Yes, I agree!
Besides, always the body will be one line in all the cases, right?

**Comment by bblimke** [comment]
Yes, body needs to be one line. We can expect to produce hundreds of lines outputs in some cases :)

**Comment by Olia-Kremmyda** [comment]
Done! :)
Is there any other relative change you would like to add here?

**Comment by bblimke** [comment]
Released as 3.3.0

**Pull request merged**
