### PR TITLE
Add rspec matcher descriptions

### PR DESCRIPTION
**Pull request by arronmabrey**
PR for Issue https://github.com/bblimke/webmock/issues/501

- refactor generation of `#failure_message` and `#failure_message_when_negated`
- add `#description` method for use in rspec matchers

### CODE REVIEW

**Comment by arronmabrey** [comment]
@bblimke FYI I think CI will fail. However before I started my PR there were 40 failing tests on master, this PR didn't cause any additional failures on my machine under ruby 2.2.2

**Comment by arronmabrey** [comment]
@bblimke any update on this?

**Comment by bblimke** [comment]
@arronmabrey sorry, I'm not able take care of it until 12th September //cc @presidentJFK

**Comment by presidentJFK** [comment]
Thanks for the submission @arronmabrey! I will take a look at this (and the failing tests) this weekend.

**Comment by presidentJFK** [comment]
closing as #511 was merged in

**Pull request closed without merging**
