### PR TITLE
Manticore adapter

### PR DESCRIPTION
**Pull request by presidentJFK**

### CODE REVIEW

**Comment by presidentJFK** [comment]
@mikeknep (and @bblimke)
I rebased your branch off master and fixed some specs for 1.8.7 support.

I also added JRuby 9.0.1.0 and 9.0.0.0 to the Travis CI build

9.0.0.0 fails on a single spec.
```ruby
 NoMethodError:
     undefined method `each_header' for "hello world":String
   # ./spec/acceptance/net_http/net_http_spec_helper.rb:35:in `__script__'
```

but I guessing this was happening on master for JRuby 9.0.0.0 also.
and it passes for JRuby 9.0.1.9, so seems like it might be a JRuby 9.0.0.0 bug.

Everything else looks good now. Just need a rebase to pick up some recent fixes.

**Comment by bblimke** [comment]
@presidentJFK :+1:

**Comment by mikeknep** [comment]
:+1: looks great!

**Comment by presidentJFK** [comment]
Awesome, I updated the Readme and I'm going to merge this in!

**Comment by ebenoist** [comment]
Amazing! Thanks @mikeknep -- I dropped this awhile ago and never picked it back up.

**Pull request merged**
